FROM ubuntu:23.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    file tree nano ca-certificates curl wget git gh build-essential zsh curl git g++ make realpath

CMD [ "/bin/bash" ]
