#!/usr/bin/env bash

COMMAND="$1"
APPNAME=ppa
VERSION="v1.0.0"

highlight() {
    if [[ -n "$(tput smul)" && -n "$(tput bold)" ]]; then
        echo $(echo -e "$1" | sed 's/\[/\\e\[4m\\e\[1m/g' | sed 's/\]/\\e\[0m/g')
    else
        echo "$1"
    fi
}


CMD_VERSION=$(highlight "[v]ersion")
CMD_HELP=$(highlight "[h]elp")
CMD_CREATE=$(highlight "[c]reate")
CMD_ACTIVATE=$(highlight "[a]ctivate")
CMD_TEST=$(highlight "[t]est")
CMD_COVERAGE=$(highlight "[c]o[v]erage")
CMD_INSTALL=$(highlight "[i]nstall")
CMD_UNINSTALL=$(highlight "[u]ninstall")


HELP=$(cat <<-EOF

Python Project Assistant (PPA) $VERSION
Usage:
    $APPNAME $CMD_VERSION                                      Returns the version of the application.
    $APPNAME $CMD_HELP                                         Show the help message.
    $APPNAME $CMD_CREATE      <project-name> [python-version]  Creates a new project.
    $APPNAME $CMD_ACTIVATE                                     Activates the current project.
    $APPNAME $CMD_TEST        [test-name]                      Runs tests.
    $APPNAME $CMD_COVERAGE    [test-name]                      Runs tests and generates coverage report. FORMAT=report format (html, xml, lcov).
    $APPNAME $CMD_INSTALL     [packages]                       Installs packages.
    $APPNAME $CMD_UNINSTALL   [packages]                       Uninstalls packages.

EOF
)

GREETER_PY=$(cat <<-EOF
def greet(name: str) -> None:
    return f"Hello, {name}!"
EOF
)

MAINPY=$(cat <<-EOF
import greeter
def main():
    print(greeter.greet("World"))

if __name__ == "__main__":
    main()
EOF
)

TEST_GREETER_PY=$(cat <<-EOF
import greeter
def test_greet():
        assert greeter.greet("World") == "Hello, World!"
        assert greeter.greet("John") == "Hello, John!"
EOF
)

function main() {
    if [[ "$COMMAND" == "version" || "$COMMAND" == "v" ]]; then
        echo "$APPNAME-$VERSION"
        return 0
    fi
    
    if [[ "$COMMAND" == "create"    || "$COMMAND" == "c"  ]]; then shift; create    "$@" ; exit $?; fi
    if [[ "$COMMAND" == "activate"  || "$COMMAND" == "a"  ]]; then shift; activate  "$@" ; exit $?; fi
    if [[ "$COMMAND" == "test"      || "$COMMAND" == "t"  ]]; then shift; test      "$@" ; exit $?; fi
    if [[ "$COMMAND" == "coverage"  || "$COMMAND" == "cv" ]]; then shift; coverage  "$@" ; exit $?; fi
    if [[ "$COMMAND" == "install"   || "$COMMAND" == "i"  ]]; then shift; install   "$@" ; exit $?; fi
    if [[ "$COMMAND" == "uninstall" || "$COMMAND" == "u"  ]]; then shift; uninstall "$@" ; exit $?; fi
    
    if [[ "$COMMAND" == "" ]]; then
        >&2 echo "ERROR: No command specified."
        >&2 echo -e "$HELP"
        >&2 echo ""
        exit -1
    fi
    
    if [[ "$COMMAND" != "help" && "$COMMAND" != "h" && "$COMMAND" != "--help" && "$COMMAND" != "-h" ]]; then
        >&2 echo "ERROR: Unknown command: '$COMMAND'."
        >&2 echo -e"$HELP"
        >&2 echo ""
        exit -1
    fi
    
    echo -e "$HELP"
}


function create() {
    PROJECT_NAME=$1
    PYTHON_VERSION=$2
    
    if [[ "$PROJECT_NAME" == "" ]]; then
        >&2 echo "ERROR: No project name specified."
        return -1
    fi
    
    if [[ "$PYTHON_VERSION" == "" || "$PYTHON_VERSION" == "system" ]] ; then
        LATEST=$(pyenv install -l | grep -Eo "^ *[1-9]+\\.[0-9]+\\.[0-9]+$" | tail -n 1 | grep -Eo "[^ ]+")
        echo "No specific version of Python given, use the default: $LATEST"
        PYTHON_VERSION="$LATEST"
    fi
    
    if [[ "$(command -v pyenv)"  == "" ]]; then >&2 echo "ERROR: 'pyenv' is not installed."  ; return -1 ;fi
    if [[ "$(command -v pipenv)" == "" ]]; then >&2 echo "ERROR: 'pipenv' is not installed." ; return -1 ; fi
    
    # Check if the --install-python flag exists and remove it from the arguments
    if [[ "$*" == *"--install-python"* ]]; then
        INSTALL_PYTHON=true
        set -- "${@/--install-python/}"
    fi
    
    # echo "PYTHON_VERSION: $PYTHON_VERSION"
    VERSIONS=$(export VERSION="$PYTHON_VERSION" ; pyenv versions --bare | grep -E "^(`echo "$VERSION" | sed 's/[.]/\\./g'`\.|$VERSION"$")")
    VERCOUNT=$(echo $VERSIONS | wc -l | grep -Eo "[0-9]+")
    
    # Check if the Python version is already installed
    if [[ "$VERCOUNT" == "0" ]] ; then
        # Check if the --install-python flag was provided or ask the user
        if [[ $INSTALL_PYTHON == true ]]; then
            # Install the Python version without asking
            echo "Installing Python $PYTHON_VERSION..."
            pyenv install $PYTHON_VERSION
        else
            if [[ "$PYTHON_VERSION" != "" ]] ; then
                # Ask the user before installing the Python version
                echo -n "Python $PYTHON_VERSION is not installed. Do you want to install it? (y/n): "
                read install_choice 
                if [[ $install_choice == [Yy] ]]; then
                    echo "Installing Python $PYTHON_VERSION..."
                    pyenv install $PYTHON_VERSION
                else
                    echo "Here are available Python versions found: "
                    pyenv versions
                    echo -n "Type the version you prefer or 'quit' to stop: "
                    read install_choice

                    if [[ $install_choice == quit ]]; then
                        echo "Bye ..."
                        return -1
                    else
                        PYTHON_VERSION="$install_choice"
                        echo "Installing Python $PYTHON_VERSION..."
                        pyenv install $PYTHON_VERSION
                    fi
                fi
            fi
        fi
    elif [[ "$VERCOUNT" != "1" ]] ; then
        echo "Here are available Python versions found: "
        pyenv versions
        echo -n "Type the version you prefer or 'quit' to stop: "
        read install_choice

        if [[ $install_choice == quit ]]; then
            echo "Bye ..."
            return -1
        else
            PYTHON_VERSION="$install_choice"
            echo "Installing Python $PYTHON_VERSION..."
            pyenv install $PYTHON_VERSION
        fi
    fi
    
    if [[ "$PYTHON_VERSION" != "" ]] ; then
        pyenv local "$PYTHON_VERSION"
        if [ $? -eq 1 ]; then
            exit
        fi
    fi
    
    mkdir -p "$PROJECT_NAME"
    pushd "$PROJECT_NAME" > /dev/null
    
    pipenv --python $PYTHON_VERSION
    
    mkdir  src
    mkdir  tests
    touch  src/__init__.py
    touch  tests/__init__.py
    
    echo "htmlcov"   >> .gitignore
    echo ".coverage" >> .gitignore
    
    printf '%s\n' "$GREETER_PY"      > src/greeter.py
    printf '%s\n' "$MAIN_PY"         > src/main.py
    printf '%s\n' "$TEST_GREETER_PY" > tests/test_greeter.py
    
    pipenv install pytest pylint coverage pytest-cov --dev
    
    local PREV_PYTHONPATH="$PYTHONPATH"
    local NEW_PYTHONPATH="$(pwd)/src:$PYTHONPATH"
    local RUN_FILE=$(mktemp)
    echo "#!$SHELL"                               >  "$RUN_FILE"
    echo "export PYTHONPATH=$NEW_PYTHONPATH"      >> "$RUN_FILE"
    echo "pipenv shell --python $PYTHON_VERSION"  >> "$RUN_FILE"
    chmod 755 "$RUN_FILE"
    "$RUN_FILE"

    PYTHONPATH="$PREV_PYTHONPATH"
}

function init() {
    PROJECT_PATH=$1
    PYTHON_VERSION=$2

    ABS_PATH=$(realpath "$PROJECT_PATH")
    PARENT_PATH=$(dirname "$ABS_PATH")
    PROJECT_NAME=$(basename "$ABS_PATH")

    pushd "$PARENT_PATH"
    create "$PROJECT_NAME" "$PYTHON_VERSION"
}

function ensure-activated() {
    if [[ "$VIRTUAL_ENV" == "" ]]; then
        echo "Virtual environment is not activated. Please activate it first."
        exit
    fi
}

function activate() {
    if [[ "$VIRTUAL_ENV" != "" ]]; then
        echo "Virtual environment already activated."
        exit
    fi
    
    local PREV_PYTHONPATH="$PYTHONPATH"
    local NEW_PYTHONPATH="$(pwd)/src:$PYTHONPATH"
    echo "Activating virtual environment ..."
    echo "Type 'exit' to deactivate the environment."
    echo ""

    local RUN_FILE=$(mktemp)
    echo "#!$SHELL"                              >  "$RUN_FILE"
    echo "export PYTHONPATH=$NEW_PYTHONPATH"     >> "$RUN_FILE"
    echo "pipenv install --dev --ignore-pipfile" >> "$RUN_FILE"
    echo "pipenv shell"                          >> "$RUN_FILE"
    chmod 755 "$RUN_FILE"
    "$RUN_FILE"

    echo "Bye ..."
    PYTHONPATH="$PREV_PYTHONPATH"
}

function test() {
    ensure-activated
    
    if [ $# -eq 0 ]; then
        pytest tests/
    else
        pytest "$@"
    fi
}

function coverage() {
    ensure-activated
    
    FORMAT=${FORMAT:-term}
    pytest --cov=src --cov-report=$FORMAT tests/

    if [[ "$FORMAT" == "html" && "$(command -v open)" != "" ]]; then
        open htmlcov/index.html
    fi
}

function install() {
    ensure-activated
    pipenv install "$@"
}

function uninstall() {
    ensure-activated
    pipenv uninstall "$@"
}

main "$@"
